CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(30) NOT NULL, 
    email VARCHAR(100) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    emailVerified BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);